name: load testing

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js and npm
      uses: actions/setup-node@v6.2.0
    #   # with:
    #   #   node-version: ${{ matrix.node-version }}

    # - name: setup
    #   run: |
    #     sh load_test.sh

    - name: check vars
      run: |
        echo ${{ vars.DATA }}

    # - name: load test
    #   run: |
    #     autocannon -p 5 -a 50 -m POST -H "Content-Type: application/json" -b '${{ vars.DATA }}' ${{ vars.ENDPOINT }}
