name: load testing

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js and npm
      uses: actions/setup-node@v6.2.0

    - name: load test
      run: |
        sh load_test.sh

    # - name: check vars
    #   run: |
    #     sudo npm install -g autocannon
    #     echo autocannon -v

    # - name: load test
    #   run: |
    #     autocannon -p 5 -a 50 -m POST -H "Content-Type: application/json" -b '${{ secrets.DATA }}' ${{ vars.ENDPOINT }}
